# Generated by Django 3.2.18 on 2023-02-27 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yannjuApp', '0005_auto_20230228_0317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='modify_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
